### ISSUE TITLE
Configurations with one item not merging as same object type as multiple configurations

### ISSUE THREAD

**Issue by thomwatt** [gaelcolas/datum#74] opened 2019-07-01 16:14 UTC
I have example files that demonstrate this issue at https://github.com/thomwatt/datum

If you have a look at Datum.ps1 and once run, look at the $TableData object. The output should return a collection of Windows shares with properties:
•StartupType
•Name
•State

If you look at the output below, it returns objects for the services taken from \Tibco\FTL.yml but for the service taken from \Tibco\Base.yml it is returning key/value pairs (the last 3 objects in the YAML below).

This behaviour only happens if the base.yml file contains one service definition. If it has 2 or more, the output is perfect

- StartupType: Automatic
  Name: tibJettySvc
  State: Running
- StartupType: Automatic
  Name: tibrealmserver
  State: Running
- StartupType: Automatic
  Name: tibrealmserver-as
  State: Running
- StartupType: Automatic
  Name: tibstore
  State: Running
- Key: StartupType
  Value: Automatic
- Key: Name
  Value: Base Service
- Key: State
  Value: Running

Following our discussion you thought that this may be a bug that you had spotted but not yet released the fix for.

**Comment by fullenw1** [comment] 2020-01-16 10:44
Hi @thomwatt 
I think I have the same type of issue but your link [https://github.com/thomwatt/datum](https://github.com/thomwatt/datum) is not working anymore.
So for the moment I don't know if I should add more information to this issue or open new one...

**Comment by HansOMartinsen** [comment] 2020-03-24 07:35
I now have the exact same problem. I solve it by having a "dummy" entry at the "global" level. Then the merge works as expected. @gaelcolas : Something you have experienced before?

**Comment by thomwatt** [comment] 2020-03-24 08:20
First of all, I'm using datum for defining configuration that is used to generate Pester tests that validate infrastructure desired state against actual state. I do not use DSC.

I did manage to resolve my problem by working on the datum definition YAML file - the one that defines order of precedence and merge behaviour. I found (from memory) that one of the merge types I was using wasn't implemented in the datum module so I stopped using that. Unfortunately the documentation around merge configuration is not comprehensive (I think its a work in progress) so with a bit of trial and error, I managed to configure Datum in a way that works for me and I am now using it without issue. I have an extract from on of my datum definition files below - maybe you can use my merge configuration with your setup.

ResolutionPrecedence:
  - 'Node\$($node.Nodename)' # What makes this node unique to all the other nodes of the same type.
  - 'Role\$($node.WorkStream)\$($node.Role)\$($node.Environment)\$($node.Role)' # What all nodes have in common, specific to a particular role and specific to an environment. 
  - 'Role\$($node.WorkStream)\$($node.Role)\Base' # What all nodes have in common, specific to a particular Role, across all Environments.
  - 'Role\$($node.WorkStream)\Base' # What all nodes have in common, specific to the  Workstream, across all Roles and Environments.
  - 'Location\$($node.Location)' # What all nodes have in common based on their hosting location
  - 'Environment\$($node.Environment)' # What all nodes have in common, irrelevant of the workstream, but Environment specific.
  - 'Node\All' # What all nodes have in common, irrelevant of Workstream or Environment.
lookup_options:
  configurations:
    merge_basetype_array: Unique
  Shares:
    merge_hash: deep
    merge_basetype_array: Sum
    merge_hash_array: UniqueKeyValTuples
    merge_options:
      tuple_keys:
        - Path
  Packages:
    merge_hash: deep
    merge_basetype_array: Sum
    merge_hash_array: UniqueKeyValTuples
    merge_options:
      tuple_keys:
        - ProductId    
  Services:
    merge_hash: deep
    merge_basetype_array: Sum
    merge_hash_array: UniqueKeyValTuples
    merge_options:
      tuple_keys:
        - Name
  WindowsFeatures:
    merge_hash: deep
    merge_basetype_array: Sum
    merge_hash_array: UniqueKeyValTuples
    merge_options:
      tuple_keys:
        - Name
  WebApplications:
    merge_hash: deep
    merge_basetype_array: Sum
    merge_hash_array: UniqueKeyValTuples
    merge_options:
      tuple_keys:
        - Name 
  Certificates:
    merge_hash: deep
    merge_basetype_array: Sum
    merge_hash_array: UniqueKeyValTuples
    merge_options:
      tuple_keys:
        - Subject
  HostFileEntries:
    merge_hash: deep
    merge_basetype_array: Sum
    merge_hash_array: UniqueKeyValTuples
    merge_options:
      tuple_keys:
        - IPAddress

**Comment by gaelcolas** [comment] 2020-07-24 07:51
I think that's just been fixed by @ykuijs.
PR has beem merged, will notify here when the new version has been released.

**Comment by gaelcolas** [comment] 2020-08-10 03:25
please check the module version 0.39.0-preview0001 for a fix.
Re-open with details if further issues.

thanks @ykuijs

**Comment by fullenw1** [comment] 2020-08-12 17:00
Unfortunately, I am not able to load the module version 0.0.39-preview0001

I have:
1. Downloaded and extracted the Zip file
2. Copied the content of the **Source** folder to a 0.0.39 subfolder of the Datum folder.

In addition, I had to:
1. Replace `ModuleVersion     = '0.0.1'`  with `ModuleVersion     = '0.0.39'` inside the PSD1 file
2. Replace `FunctionsToExport = ' '`  with `FunctionsToExport = '*'` inside the PSD1 file
3. Replace `AliasesToExport   = ' '`  with `AliasesToExport   = '*'` inside the PSD1 file
3. Uncomment the content of the PSM1 file

The module is now loading but with a lot of these errors:
```powershell
Unable to find type [DatumProvider]

Unable to find type [FileProvider]
```

**Comment by gaelcolas** [comment] 2020-08-12 21:09
Thanks, gonna check this when I'm home this weekend.

**Comment by gaelcolas** [comment] 2020-08-17 14:55
Ah yeah, now that I'm reading this @fullenw1, you got it the wrong way.
You can `Install-Module -Name Datum -AllowPrerelease`.

You should not go through the source like that.

Alternatively if you've cloned the repo `git clone git@github.com:gaelcolas/datum.git`, you should be able to just build it locally calling `build.ps1`.

It will take some time to pull the dependencies it needs for building it, and then it will build in the output folder and be available in your session (and version will be off if you haven't installed GitVersion).

**Comment by gaelcolas** [comment] 2020-08-17 14:56
some more details here: https://dsccommunity.org/blog/convert-a-module-for-continuous-delivery/
that's a bit old and things have evolved since then, but shows the principles.

**Comment by fullenw1** [comment] 2020-09-22 18:06
@gaelcolas 

The installation with `Install-Module -Name Datum -AllowPrerelease` works fine. Thanks!
However I still have the same errors.

I have attached a little POC for demo so you can reproduce the issue on your side :)
[DatumData.zip](https://github.com/gaelcolas/datum/files/5263196/DatumData.zip)

Everything is happening at the **Role** level.
There is a single feature in the **Baseline** et there are two features in the **FileServer** and **WebServer** roles.

With version 0.0.38 I have this wrong behavior:

```powershell
Import-Module -Name 'datum' -RequiredVersion '0.0.38'

$Datum = New-DatumStructure -DefinitionFile .\DatumData\DatumConfiguration.yml

Resolve-Datum -DatumTree $Datum -Node $Datum.AllNodes.Comp1 -PropertyPath PSDscResources\WindowsFeature

IsReadOnly     : False
IsFixedSize    : False
IsSynchronized : False
Keys           : {IncludeAllSubFeature, Name, Ensure}
Values         : {False, FS-FileServer, Present}
SyncRoot       : System.Object
Count          : 3

IsReadOnly     : False
IsFixedSize    : False
IsSynchronized : False
Keys           : {IncludeAllSubFeature, Name, Ensure}
Values         : {True, Telnet-Client, Absent}
SyncRoot       : System.Object
Count          : 3

Key   : IncludeAllSubFeature
Value : True
Name  : IncludeAllSubFeature

Key   : Name
Value : FS-SMB1
Name  : Name

Key   : Ensure
Value : Absent
Name  : Ensure
```

And with version 0.39.0 I have a lot of these errors:

```powershell
Import-Module -Name 'datum' -RequiredVersion '0.39.0'

$Datum = New-DatumStructure -DefinitionFile .\DatumData\DatumConfiguration.yml

Resolve-Datum -DatumTree $Datum -Node $Datum.AllNodes.Comp1 -PropertyPath PSDscResources\WindowsFeature

Unable to find type [DatumProvider].
At C:\Program Files\WindowsPowerShell\Modules\datum\0.39.0\datum.psm1:136 char:67
+ ... putObject -is [psobject] -or $InputObject -is [DatumProvider]) -and $ ...
+                                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (DatumProvider:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
 
Unable to find type [FileProvider].
At C:\Program Files\WindowsPowerShell\Modules\datum\0.39.0\datum.psm1:821 char:5
+     [FileProvider]::new($Path, $Store,$DatumHierarchyDefinition)
+     ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (FileProvider:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```

**Comment by gaelcolas** [comment] 2020-09-22 18:46
Thanks @fullenw1 I've started looking it at it, and I see an error on the CI pipeline.
I couldn't get the test to error locally so your sample will help.
If you have a chance, can you try in PS7 and let me know if it errors the same way?
Will report, when I get a chance to find something.

**Comment by fullenw1** [comment] 2020-09-22 19:42
Here is the result with PS7 and Datum 0.0.38

```powershell
PS> Resolve-Datum -DatumTree $Datum -Node $Datum.AllNodes.Comp1 -PropertyPath PSDscResources\WindowsFeature

System.Collections.Hashtable
System.Collections.Hashtable

Name                           Value
----                           -----
Name                           FS-SMB1
IncludeAllSubFeature           True
Ensure                         Absent
```

And here is the result with PS7 and Datum 0.39.0
(in fact many of these lines)

```powershell
InvalidOperation: C:\Program Files\PowerShell\7\Modules\datum\0.39.0\datum.psm1:136
Line |
 136 |  … putObject -is [psobject] -or $InputObject -is [DatumProvider]) -and $ …
     |                                                  ~~~~~~~~~~~~~~~
     | Unable to find type [DatumProvider].

InvalidOperation: C:\Program Files\PowerShell\7\Modules\datum\0.39.0\datum.psm1:821
Line |
 821 |      [FileProvider]::new($Path, $Store,$DatumHierarchyDefinition)
     |      ~~~~~~~~~~~~~~
     | Unable to find type [FileProvider].
```

**Comment by gaelcolas** [comment] 2020-09-22 20:40
I think/hope I found the issue.

Case sensitivity on Linux as this is where the module is built in the pipeline, and what gets published.
The build automation expects the `Classes` folder, but gets the `classes` folder which does not exist (on Linux).

**Comment by gaelcolas** [comment] 2020-09-22 20:53
I released a new pre-release version: `0.39.0-preview0002`.
You can install it like so: `Install-module -AllowPrerelease datum -Force`

Your sample should now work! My apologies!

**Comment by fullenw1** [comment] 2020-09-23 09:21
Great! It's working fine now :)
Il will try it in production...
Thank you very much!!!

**Comment by gaelcolas** [comment] 2020-09-23 10:19
thanks, let me know if the multiple/single object merge is fixed, or provide more details on your test.

**Comment by fullenw1** [comment] 2020-09-29 15:26
@gaelcolas 

I've used the preview version in production this afternoon and I could finally remove all those fake entries.
I guess the final release issued a few minutes ago is the same.
Thanks for your support :)

**Comment by gaelcolas** [comment] 2020-09-29 15:34
Yeah, I tested that version & so did Yurick so I'm pretty confident it's fine.

**Closed by gaelcolas** 2020-09-29 15:34 UTC
