### ISSUE TITLE
The given assembly name or codebase was invalid

### ISSUE THREAD

**Issue by raandree** [gaelcolas/Datum#69] opened 2019-01-22 23:43 UTC
Since upgrading to Datum 0.0.36 the CommonTasks project does no longer build on AppVeyor. When starting the build on the AppVeyor host via RDP manually, it work in PowerShell 5 and 6.

The error is this one: https://ci.appveyor.com/project/AutomatedLab/commontask/builds/21816268.

```
The 'Microsoft.PowerShell.Management' module was not imported because the 'Microsoft.PowerShell.Management' snap-in was already imported.
The 'Microsoft.PowerShell.Management' module was not imported because the 'Microsoft.PowerShell.Management' snap-in was already imported.
PSDesiredStateConfiguration\Configuration : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At C:\projects\commontask\BuildOutput\Modules\CommonTasks\DSCResources\FilesAndFolders\FilesAndFolders.schema.psm1:1 char:1
+ Configuration FilesAndFolders {
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Configuration], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Configuration
 
    [-] FilesAndFolders Compiles 2.67s
```

**Comment by gaelcolas** [comment] 2019-01-23 05:14
That seems to be unrelated to **Datum**.

The problem is that you're relying on Datum for the `Get-DscSplattedResource` which has been **removed** in this new version (as per release notes).

Please use `DscBuildHelpers` instead, it now (0.0.36 iirc) contains the `Get-DscSplattedResource` function you need.

**Comment by raandree** [comment] 2019-01-23 08:10
The error does not say that the cmdlet cannot be found. I have added the DscBuildHelpers module to the dependancies and the build runs on my machine and on AppVeyor when started manually on their host via RDP. And the issue is only with the FilesAndFolders configuration.

**Comment by gaelcolas** [comment] 2019-01-23 08:32
Please check https://ci.appveyor.com/project/AutomatedLab/commontask/builds/21823666

Seems to be working, and the error is only a warning... I don't think the issue is relevant to Datum. It could be the appveyor image, or something required by the DSC Resources/Pester or something that has changed without us knowing about it.

You could try building an old commit with Datum 0.0.35 to confirm, but at least the build is working right now...

Closing this issue here. Feel free to open one in DscWorkshop if you wanna carry on the discussion.

**Closed by gaelcolas** 2019-01-23 08:32 UTC
